/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TechAssessment;

import TechAssessment.CLIInterface.CLIDaemon;
import TechAssessment.CLIInterface.views.InitialView;

public class TechAssessMain {
    
	public static void main(String[] args){
		InitialView view = new InitialView();
        CLIDaemon daemon = new CLIDaemon(view);
        daemon.run();
    }
}
